### ISSUE TITLE
Creating repos

### ISSUE THREAD

**Issue by gowther-zoho** [vim-scraper/vim-scraper#91]
You shouldn't be creating new repos for vimscripts that never had one. For example, you created a github repo for logpad.vim where it didn't have one before. That is not good. Linking to other repos is fine.

**Comment by bronson** [comment]
That was the whole point.  It unified distribution so tools like Vundle could use plugins with obsolete package formats.

Happily, since pretty much all Vim plugins are available on Github now, there's not much need for vim-scripts anymore.  It'll go away soon.  (where "soon" is months or years, whenever the project owners get around to it)

**Comment by bronson** [comment]
Leaving this issue open until everything gets deleted.

**Comment by tmc** [comment]
@bronson where's the right place to talk about how to get the project running again? I'd be willing to contribute some time/money. Who has credentials?

**Comment by sabrons** [comment]
Well right on. The first thing to do would be to get the scraper running again, which might take some code changes. Clone vim-scraper and follow the instructions in https://github.com/vim-scraper/vim-scraper/blob/master/scraper

Once you can get a full scrape, we'll figure out how you can scrape onto the existing repos and push the updates. It will probably involve https://github.com/vim-scraper/vim-scraper/blob/master/check-remotes

Two gems make me very uneasy: hpricot and gitrb. If you can manage to replace them with Nokogiri and maybe libgit2, then the scraper is ready for a new decade. If not, then I think its days should be limited...

Good luck! Have fun with it. Feel free to open issues with any questions you have.

**Comment by bronson** [comment]
Well right on. The first thing to do would be to get the scraper running again, which might take some code changes. Clone vim-scraper and follow the instructions in https://github.com/vim-scraper/vim-scraper/blob/master/scraper

Once you can get a full scrape, we'll figure out how you can scrape onto the existing repos and push the updates. It will probably involve https://github.com/vim-scraper/vim-scraper/blob/master/check-remotes

Two gems make me very uneasy: hpricot and gitrb. If you can manage to replace them with Nokogiri and maybe libgit2, then the scraper is ready for a new decade. If not, then I think its days should be limited...

Good luck! Have fun with it. Feel free to open issues with any questions you have.

**Comment by tmc** [comment]
current status...

```
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mail'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Class)
Backtrace for gem load error is:
/home/user/go/src/github.com/vim-scraper/vim-scraper/vendor/bundle/ruby/1.9.1/gems/mail-2.2.19/lib/mail.rb:15:in `require'
/home/user/go/src/github.com/vim-scraper/vim-scraper/vendor/bundle/ruby/1.9.1/gems/mail-2.2.19/lib/mail.rb:15:in `<module:Mail>'
/home/user/go/src/github.com/vim-scraper/vim-scraper/vendor/bundle/ruby/1.9.1/gems/mail-2.2.19/lib/mail.rb:2:in `<top (required)>'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
/home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
./scraper:78:in `<main>'
Bundler Error Backtrace:
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
	from /home/user/.rbenv/versions/1.9.2-p330/lib/ruby/gems/1.9.1/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
	from ./scraper:78:in `<main>'
```

**Comment by tmc** [comment]
Ping
